# Generated by Django 2.0.6 on 2018-06-18 12:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Boote',
            },
        ),
        migrations.CreateModel(
            name='Reservierung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_Datum', models.DateField(default=datetime.date.today, verbose_name='Start Datum')),
                ('e_Datum', models.DateField(default=datetime.date.today, verbose_name='End Datum')),
                ('a_Zeit', models.TimeField(verbose_name='Reserviert von')),
                ('e_Zeit', models.TimeField(verbose_name='Reserviert bis')),
                ('reserviert_von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reserviert', to=settings.AUTH_USER_MODEL)),
                ('reserviertesBoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservierung.Boot')),
            ],
            options={
                'verbose_name_plural': 'Reservierungen',
                'ordering': ['reserviertesBoot', 'a_Datum', 'a_Zeit'],
            },
        ),
    ]
