# Generated by Django 2.0.6 on 2018-07-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservierung', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservierung',
            options={'ordering': ['reserviertesBoot', 'a_Datum'], 'verbose_name_plural': 'Reservierungen'},
        ),
        migrations.RemoveField(
            model_name='reservierung',
            name='a_Zeit',
        ),
        migrations.RemoveField(
            model_name='reservierung',
            name='e_Zeit',
        ),
    ]
