# Generated by Django 2.0.6 on 2018-07-09 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservierung', '0002_auto_20180709_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einweisung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('einweisung', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/uploads/', verbose_name='Image')),
            ],
        ),
        migrations.AddField(
            model_name='boot',
            name='instandsetzung',
            field=models.TextField(default='Keine Instandsetzungen notwendig'),
        ),
        migrations.AddField(
            model_name='images',
            name='boot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservierung.Boot'),
        ),
        migrations.AddField(
            model_name='einweisung',
            name='boot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservierung.Boot'),
        ),
        migrations.AddField(
            model_name='einweisung',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
