# Generated by Django 2.0.6 on 2018-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservierung', '0003_auto_20180709_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='einweisung',
            options={'verbose_name_plural': 'Einweisungen'},
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
