# Generated by Django 2.0.6 on 2018-07-19 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservierung', '0004_auto_20180719_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instandsetzung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eintrag', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='boot',
            name='instandsetzung',
        ),
        migrations.AddField(
            model_name='instandsetzung',
            name='boot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservierung.Boot'),
        ),
    ]
