# Generated by Django 2.0.6 on 2018-07-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservierung', '0005_auto_20180719_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
