# Generated by Django 2.0.6 on 2018-07-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservierung', '0006_auto_20180721_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
