# Generated by Django 2.0.6 on 2018-08-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservierung', '0007_auto_20180721_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='info',
            field=models.TextField(default='Keine Information Verfügbar'),
        ),
    ]
