# Generated by Django 2.0.6 on 2018-08-02 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservierung', '0008_boot_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='einweisung',
            options={'ordering': ['boot'], 'verbose_name_plural': 'Einweisungen'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['boot']},
        ),
        migrations.AlterModelOptions(
            name='instandsetzung',
            options={'ordering': ['boot']},
        ),
        migrations.AddField(
            model_name='instandsetzung',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
