# Generated by Django 2.0.6 on 2019-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservierung', '0010_auto_20190306_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boot',
            options={'ordering': ['name'], 'verbose_name_plural': 'Boote'},
        ),
        migrations.AddField(
            model_name='instandsetzung',
            name='durchfuehrung_durch',
            field=models.CharField(default=None,null=True ,max_length=255),
        ),
        migrations.AddField(
            model_name='instandsetzung',
            name='geplant_am',
            field=models.DateTimeField(default=None,null=True),
        ),
    ]
