# Generated by Django 2.0.6 on 2019-03-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservierung', '0013_auto_20190307_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instandsetzung',
            name='geplant_am',
            field=models.DateField(default=None, null=True),
        ),
    ]
